### ISSUE TITLE
Unable to login to MAL tracker

### ISSUE THREAD

**Issue by Etheride** [Saud-97/TachiyomiS97#1]
### Steps to reproduce

1. Open the app
2. Go to Settings > Tracker
3. Login to MyAnimeList after clicking on the MyAnimeList button
4. When logged in, you are redirected to TachiyomiJ2K

Video of shown issue: https://media.discordapp.net/attachments/1002106359183061073/1002296058510069820/Screen_Recording_20220729-012525_TachiyomiJ2K.mp4

### Expected behavior

After logging into MAL, the user should be redirected back to TachiyomiS97 and the tracker should list MAL as one of the tracked websites on the apl

### Actual behavior

The App does not recognise the user logging into MAL, thus will show that the user has to still log in into MAL

### TachiyomiS97 version

1.5.6

### Android version

Android 12 

### Device

Samsung A52s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the **[latest version](https://github.com/saud-97/TachiyomiS97/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Saud-97** [comment]
I have found the root cause of the issue. Most likely this will be addressed in the next release.

**Comment by Saud-97** [comment]
The issue was fixed. Let me know if there was any issues after the new update.
